server:
  port: 8081
spring:
  application:
    name: AccountConsumerApplication
  redis:
    host: localhost
    port: 6379

eureka:
  instance:
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}
    hostname: account-consumer.mikusun.club
    appname: Account-Consumer-Application
    ip-address: account-consumer.mikusun.club
    prefer-ip-address: true
    non-secure-port: 80
    non-secure-port-enabled: false
    home-page-url: http://${eureka.instance.hostname}
    status-page-url: http://${eureka.instance.hostname}/actuator/info
    health-check-url: http://${eureka.instance.hostname}/actuator/health
  client:
    # 声明是否将自己的信息注册到 Eureka 服务器上
    register-with-eureka: true
    # 是否到 Eureka 服务器中抓取注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://eureka.mikusun.club/eureka

mikusun:
  shiro:
    auth_method: authc
