server:
  port: 8080
spring:
  application:
    name: AccountProvideApplication
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  datasource:
    url: jdbc:mysql://47.103.9.132:3306/account
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: mysql
    show-sql: true
    hibernate:
#       应用启动时检测表结构,不同则更新结构
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.format_sql: true

  redis:
    host: localhost
    port: 6379
#logging:
#  level:
#    root: debug


eureka:
  instance:
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}
    hostname: account-provide.mikusun.club
    appname: Account-Provide-Application
    ip-address: account-provide.mikusun.club
    prefer-ip-address: true
    non-secure-port: 80
    non-secure-port-enabled: false
    home-page-url: http://${eureka.instance.hostname}
    status-page-url: http://${eureka.instance.hostname}/actuator/info
    health-check-url: http://${eureka.instance.hostname}/actuator/health
  client:
    # 声明是否将自己的信息注册到 Eureka 服务器上
    register-with-eureka: true
    # 是否到 Eureka 服务器中抓取注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://eureka.mikusun.club/eureka
